### PR TITLE
Radiation pressure models

### PR DESCRIPTION
**Pull request by DominikStiller**
This PR introduces a new set of radiation pressure models. Before, only solar radiation was supported. Now, planetary radiation (albedo, thermal, ...) can be considered, and the paneled spacecraft model has more features. The classes are designed to be extended.

The primary models added here are (all `tudat::electromagnetism`):
* `RadiationPressureAcceleration`: a single acceleration for all types of sources and targets, as opposed to multiple before
* `RadiationSourceModel`: an environment model describing how a body emits radiation (point or extended/paneled)
* `RadiationPressureTargetModel`: an environment model describing how a body is accelerated by radiation (cannonball or paneled)

These classes have many sub- and related classes, all of which are unit tested. There were small discrepancies in the validation, which may or may not indicate issues with the implementation.

The models were implemented for [this paper](http://resolver.tudelft.nl/uuid:8a82400a-2233-4a84-98be-ed37f7eeb620), which contains a description of the core equations. Related analysis code is available in [this repositoy](https://github.com/DominikStiller/tudelft-hpb-project).

PR for Documentation: https://github.com/tudat-team/tudat-space/pull/122

To do after merging:
* Create tudatpy interface
* Extract docstrings to multidoc
* Remove code for old radiation pressure models (marked with `// RP-OLD`)
* Possibly deprecate the old interface (keep both for a while), or adjust the new models to the old one
* Adapt estimation of cannonball parameters

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Thanks for developing al this, it's going to make a very important addition to Tudat!

I'm compiling your code, and am running into the following error in a unit test compilation:

```
/home/dominic/Tudat/tudat-bundle/tudat-bundle/tudat/tests/src/astro/electromagnetism/unitTestSourcePanelRadiosityModel.cpp:94:54: error: no matching function for call to ‘tudat::electromagnetism::AlbedoSourcePanelRadiosityModel::updateOriginalSourceProperties(int, const NegativeReturnType)’
   94 |         radiosityModel.updateOriginalSourceProperties(1, -Eigen::Vector3d::UnitX());
```

The `updateOriginalSourceProperties` function that is being called has the following function signature, which indeed does not match the one above.

```
 void updateOriginalSourceProperties(
            double originalSourceUnoccultedIrradiance,
            double originalSourceOccultedIrradiance,
            const Eigen::Vector3d& originalSourceToPanelDirection)
```

I'm assuming that, in these tests, originalSourceUnoccultedIrradiance and originalSourceOccultedIrradiance should be set to be equal to one another (e.g. no effect of occultation). Can you confirm this interpretation?

**Comment by DominicDirkx** [comment]
Update: I've traced the issue to this:
```

else if( bodyName == "Earth" )
    {
        // Model from Knocke (1988)
        radiationSourceModelSettings =
                extendedRadiationSourceModelSettings({
                    albedoPanelRadiosityModelSettings(SecondDegreeZonalPeriodicSurfacePropertyDistributionModel::albedo_knocke, "Sun"),
                    delayedThermalPanelRadiosityModelSettings(SecondDegreeZonalPeriodicSurfacePropertyDistributionModel::emissivity_knocke, "Sun")
                }, {6, 12});
    }
```

default Earth setting, which requires the Sun to be created if a default Earth is created. I don't think this is a good requirement, and I've commented this out for now

**Comment by DominikStiller** [comment]
Thanks for catching those failed unit tests, I should have checked them before committing. I've integrated your improvements into my branch and they should pass now.

Regarding the default Earth model, I've commented out those lines now. A default source for Earth worked before, but I refactored the dependency on the original source (inherent sources are now natively supported without workaround!), which broke the default.

**Comment by DominicDirkx** [comment]
Awesome, thanks! I can confirm that the unit tests are all passing now :)

**Comment by DominikStiller** [comment]
I think unifying target panels for aerodynamic and radiation pressure into a single geometric model makes a lot of sense, and the dynamic panel orientation will be very useful. So no concerns from my side!

**Pull request merged**
